pipeline {
    agent { 
        node {
            label 'docker-agent-python'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                    cd jenkins/myapp
                    pip install -r requirements.txt --break-system-packages
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                    cd jenkins/myapp
                    python3 hello.py
                    python3 hello.py --name=Brad
                '''
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                    echo "doing delivery stuff.."
                '''
            }
        }
    }
}

